Port = 5922
HostKey = """
-----BEGIN PRIVATE KEY-----
MFECAQEwBQYDK2VwBCIEIACJhVS3HzDrD9AnooNvIl1BTZb64HDm/0ruEv2/Fmo4gSEA7GwVSeMI\r
A+muw2ufRzzDbrA/gO1eFInwXOJNJFiZsqw=\r

-----END PRIVATE KEY-----
"""
AuthorizedKeys = ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Pa0R64MB2Qk0VRqFqT4c4iJVHWPrj4K6TLQ7O8LbKGNNyqPdQu1MbJZVYcyvvqqh/BS4VwUt2/Cv/V7eff9VcwU0TFX3dhfuezjXH9WIRaev4tJgn88FgpxGQI5cVzQyWErzMteOL3OPAiJe8C+xYSrowlTZcfE6jkyIu37RM5/oWwg/Gkf07l4kaiz8YOoM00Dvuvn/FVC5Rk2aqn4fZLyF7KFSCkTCCY+2tWJZDko3EXHy+AxBBS4Tq5r7+h6cAEBOVjgnFh3fUYpGiSJuwNWsUOanGKmMprX9ZcgUNpJZcpGDBGlWYDLEWm2ThAZT5CBSL3a+2SkMZVVSi1kn dcagent_key"]
